# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Patch
version:      0.04
version_from: lib/Config/Patch.pm
installdirs:  site
requires:
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
