#!/usr/bin/perl
###########################################
# config-patch 
# 2005, Mike Schilli <cpan@perlmeister.com>
###########################################
use strict;
use warnings;
use Getopt::Std;
use Pod::Usage;

use vars qw($CVSVERSION);

$CVSVERSION = '$Revision: 1.1 $';

getopts("hv", \my %opts);
pod2usage() if $opts{h};
if($opts{v}) {
    my ($version) = $CVSVERSION =~ /(\d\S+)/;
    die "$0 $version\n";
}

__END__

=head1 NAME

    config-patch - blah blah blah

=head1 SYNOPSIS

    config-patch -xyz

=head1 OPTIONS

=over 8

=item B<-x>

Prints this manual page in text format.

=back

=head1 DESCRIPTION

config-patch blah blah blah.

=head1 EXAMPLES

  $ config-patch -x foo bar

=head1 LEGALESE

Copyright 2005 by Mike Schilli, 
all rights reserved. This program is free 
software, you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 AUTHOR

2005, Mike Schilli <cpan@perlmeister.com>
